--PART – A:

--1. IMPLEMENT SCALAR FUNCTION TO RETURN "WELCOME TO DBMS LAB".
CREATE  FUNCTION FN_PRINT
()
RETURNS VARCHAR(50)
AS
BEGIN
RETURN 'WELCOME TO DBMS LAB'
END
SELECT DBO.FN_PRINT()

--2. IMPLEMENT SCALAR FUNCTION TO CALCULATE SIMPLE INTEREST.
CREATE FUNCTION FN_CALCULATE_SIMPLE_INTEREST
(
    @P FLOAT,
    @R FLOAT,
    @T FLOAT
)
RETURNS FLOAT
AS
BEGIN
    RETURN (@P * @R * @T) / 100
END

SELECT DBO.FN_CALCULATE_SIMPLE_INTEREST(10000, 5, 2)

--3. IMPLEMENT SCALAR FUNCTION TO FIND DIFFERENCE IN DAYS BETWEEN TWO DATES.
CREATE FUNCTION FN_DATE_DIFFERENCE
(
    @DATE1 DATE,
    @DATE2 DATE
)
RETURNS INT
AS
BEGIN
    RETURN DATEDIFF(DAY, @DATE1, @DATE2)
END

SELECT dbo.FN_DATE_DIFFERENCE('2026-01-11', '2026-09-21')

--4. IMPLEMENT SCALAR FUNCTION TO CHECK WHETHER NUMBER IS ODD OR EVEN.
CREATE FUNCTION FN_ODD_EVEN
(
    @NUM INT
)
RETURNS VARCHAR(10)
AS
BEGIN
    IF @NUM % 2 = 0
        RETURN 'Even'
    
    RETURN 'Odd'
END

SELECT dbo.FN_ODD_EVEN(10)

--5. IMPLEMENT SCALAR FUNCTION TO PRINT NUMBERS FROM 1 TO N.
CREATE FUNCTION FN_PRINT_NUMBERS
(
@N INT
)
RETURNS VARCHAR(MAX)
AS
BEGIN
    DECLARE @PRINT VARCHAR(MAX) ='';
    DECLARE @I INT = 1
      WHILE @I <= @N
    BEGIN
        SET @PRINT = @PRINT + CAST(@I AS VARCHAR) + ' '
        SET @I = @I + 1
    END

    RETURN @PRINT
END

SELECT dbo.FN_PRINT_NUMBERS(10)

--PART – B:

--6. IMPLEMENT SCALAR FUNCTION TO CALCULATE FACTORIAL OF GIVEN NUMBER.
CREATE FUNCTION FN_FACTORIAL
(
    @N INT
)
RETURNS BIGINT
AS
BEGIN
    DECLARE @FACT BIGINT = 1
    DECLARE @I INT = 1

    WHILE @I <= @N
    BEGIN
        SET @FACT = @FACT * @I
        SET @I = @I + 1
    END

    RETURN @FACT
END

SELECT dbo.FN_FACTORIAL(5)

--7. IMPLEMENT SCALAR FUNCTION TO CHECK PALINDROME NUMBER.

CREATE FUNCTION FN_PALINDROME
(
    @N INT
)
RETURNS VARCHAR(20)
AS
BEGIN
    DECLARE @TEMP INT = @N
    DECLARE @REV INT = 0
    DECLARE @REM INT

    WHILE @TEMP > 0
    BEGIN
        SET @REM = @TEMP % 10
        SET @REV = (@REV * 10) + @REM
        SET @TEMP = @TEMP / 10
    END

    IF @N = @REV
        RETURN 'Palindrome'

    RETURN 'Not Palindrome'
END

SELECT dbo.FN_PALINDROME(121)

--8. IMPLEMENT SCALAR FUNCTION TO FIND MAXIMUM OF THREE NUMBERS.
CREATE FUNCTION FN_MAX_THREE
(
    @A INT,
    @B INT,
    @C INT
)
RETURNS INT
AS
BEGIN
    DECLARE @MAX INT

    SET @MAX = @A

    IF @B > @MAX
        SET @MAX = @B

    IF @C > @MAX
        SET @MAX = @C

    RETURN @MAX
END

SELECT dbo.FN_MAX_THREE(10, 25, 15)

--9. IMPLEMENT SCALAR FUNCTION TO CALCULATE SQUARE AND CUBE OF A NUMBER.
CREATE FUNCTION FN_SQUARE_CUBE
(
    @N INT
)
RETURNS VARCHAR(100)
AS
BEGIN
    RETURN 'Square = ' + CAST(@N * @N AS VARCHAR) +
           ', Cube = ' + CAST(@N * @N * @N AS VARCHAR)
END

SELECT dbo.FN_SQUARE_CUBE(5)

--FROM THE TABLE EMPLOYEE PERFORM THE FOLLOWING QUERIES:

--PART – C:

--10. IMPLEMENT SCALAR FUNCTION TO RETURN EMPLOYEE FULL DETAILS USING EID.
CREATE FUNCTION FN_EMPLOYEE_DETAILS
(
    @EID INT
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM EMPLOYEE
    WHERE EID = @EID
)

SELECT * FROM FN_EMPLOYEE_DETAILS(105)

--11. IMPLEMENT SCALAR FUNCTION TO RETURN HIGHEST SALARY FROM A GIVEN DEPARTMENT.
CREATE FUNCTION FN_HIGH_SALARY
(
    @DEPARTMENT VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT MAX(SALARY) AS HIGHEST_SALARY
    FROM EMPLOYEE
    WHERE DEPARTMENT = @DEPARTMENT
)

SELECT * FROM FN_HIGH_SALARY('IT')

--12. IMPLEMENT SCALAR FUNCTION TO COUNT TOTAL EMPLOYEES IN EMPLOYEE TABLE.
CREATE FUNCTION FN_TOTAL_EMPLOYEES()
RETURNS TABLE
AS
RETURN
(
    SELECT COUNT(*) AS TOTAL_EMPLOYEES
    FROM EMPLOYEE
)

SELECT * FROM FN_TOTAL_EMPLOYEES()

--13. IMPLEMENT SCALAR FUNCTION TO FIND TOTAL EXPERIENCE OF EMPLOYEE USING JOININGYEAR.
CREATE FUNCTION FN_EXPERIENCE
()
RETURNS TABLE
AS
RETURN
(
    SELECT YEAR(GETDATE())-JOININGYEAR AS TOTAL_EXPERIENCE  FROM EMPLOYEE
)

SELECT * FROM FN_EXPERIENCE()

--14. IMPLEMENT SCALAR FUNCTION TO RETURN TOTAL NUMBER OF EMPLOYEES IN A GIVEN DEPARTMENT.
CREATE FUNCTION FN_DEPARTMENT_EMPLOYEES
(
    @DEPARTMENT VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT COUNT(*) AS TOTAL_EMPLOYEES
    FROM EMPLOYEE
    WHERE DEPARTMENT = @DEPARTMENT
)

SELECT * FROM FN_DEPARTMENT_EMPLOYEES('IT')

--15. IMPLEMENT SCALAR FUNCTION TO COUNT TOTAL EMPLOYEES FROM A GIVEN CITY.
CREATE FUNCTION FN_CITY_EMPLOYEES
(
    @CITY VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT COUNT(*) AS TOTAL_EMPLOYEES
    FROM EMPLOYEE
    WHERE CITY = @CITY
)

SELECT * FROM FN_CITY_EMPLOYEES('Rajkot')
