--PART – A:

--1. CREATE A STORED PROCEDURE TO GENERATE DEPARTMENT-WISE SALARY STATISTICS LIKE TOTAL SALARY, AVERAGE
--SALARY, MINIMUM SALARY, AND MAXIMUM SALARY. (USER ENTER ONLY DEPARTMENT NAME)
CREATE OR ALTER PROCEDURE SP_DEPT_SALARY
@DEPARTMENT VARCHAR(50)
AS
BEGIN
SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY,
AVG(SALARY) AS AVG_SALARY,MIN(SALARY) AS MIN_SALARY,
MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEE
WHERE DEPARTMENT=@DEPARTMENT
GROUP BY DEPARTMENT;
END

EXEC SP_DEPT_SALARY 'COMPUTER';
--2. CREATE A STORED PROCEDURE THAT ACCEPTS A JOINING YEAR AND DISPLAYS EMPLOYEES WHO JOINED THAT YEAR.

CREATE OR ALTER PROCEDURE SP_EMPLOYEE_BY_YEAR
@JOININGYEAR INT
AS
BEGIN
SELECT * FROM EMPLOYEE
WHERE JOININGYEAR=@JOININGYEAR;
END

EXEC SP_EMPLOYEE_BY_YEAR 2025;

--3. CREATE A STORED PROCEDURE FOR DYNAMIC EMPLOYEE SEARCH USING PARAMETERS (USER MAY ENTER PARTIAL CITY
--NAME).

CREATE OR ALTER PROCEDURE SP_EMPLOYEE_BY_CITY
@CITY VARCHAR(50)
AS
BEGIN
SELECT * FROM EMPLOYEE
WHERE CITY LIKE '%' + @CITY + '%';
END

EXEC SP_EMPLOYEE_BY_CITY 'RAJ';

--4. CREATE A STORED PROCEDURE THAT ACCEPTS A SALARY AMOUNT AND DISPLAYS EMPLOYEES EARNING MORE THAN THE
--ENTERED SALARY.
CREATE OR ALTER PROCEDURE SP_EMPLOYEE_BY_SALARY
@SALARY DECIMAL(7,2)
AS
BEGIN
SELECT * FROM EMPLOYEE
WHERE SALARY>@SALARY;
END

EXEC SP_EMPLOYEE_BY_SALARY 50000;
--5. CREATE A STORED PROCEDURE TO DISPLAY TOP N HIGHEST PAID EMPLOYEES FROM EACH DEPARTMENT (VALUE OF N
--IS ENTERED BY USER).
CREATE OR ALTER PROCEDURE SP_TOP_N_EMPLOYEE
@N INT
AS
BEGIN
SELECT * FROM
(
SELECT *,ROW_NUMBER() OVER
(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RN
FROM EMPLOYEE
) X
WHERE RN<=@N;
END

EXEC SP_TOP_N_EMPLOYEE 2;
--6. CREATE A STORED PROCEDURE TO INCREASE SALARY DEPARTMENT-WISE BY A GIVEN PERCENTAGE. (USER ENTER
--DEPARTMENT NAME AND %, E.G. COMPUTER 10).
CREATE OR ALTER PROCEDURE SP_INCREASE_SALARY
@DEPARTMENT VARCHAR(50),@PERCENT DECIMAL(5,2)
AS
BEGIN
UPDATE EMPLOYEE
SET SALARY=SALARY+(SALARY*@PERCENT/100)
WHERE DEPARTMENT=@DEPARTMENT;
END

EXEC SP_INCREASE_SALARY 'COMPUTER',10;
--7. CREATE A STORED PROCEDURE TO DISPLAY EMPLOYEES HAVING EXPERIENCE GREATER THAN OR EQUAL TO THE ENTERED
--YEARS.
CREATE OR ALTER PROCEDURE SP_EMPLOYEE_EXPERIENCE
@YEARS INT
AS
BEGIN
SELECT * FROM EMPLOYEE
WHERE YEAR(GETDATE())-JOININGYEAR>=@YEARS;
END

EXEC SP_EMPLOYEE_EXPERIENCE 5;
--8. CREATE A STORED PROCEDURE THAT ACCEPTS A NUMBER AS INPUT AND DISPLAYS DETAILS OF THE LAST N EMPLOYEES
--WHO JOINED THE ORGANIZATION.
CREATE OR ALTER PROCEDURE SP_LAST_N_EMPLOYEE
@N INT
AS
BEGIN
SELECT TOP (@N) * FROM EMPLOYEE
ORDER BY JOININGYEAR DESC,EID DESC;
END

EXEC SP_LAST_N_EMPLOYEE 5;
--FROM THE TABLE AUTHOR, PUBLISHER AND BOOK PERFORM THE FOLLOWING QUERIES:

--PART – B:

--9. CREATE A STORED PROCEDURE THAT ACCEPTS AN AUTHOR NAME AND DISPLAYS ALL BOOKS WRITTEN BY THAT AUTHOR.

CREATE OR ALTER PROCEDURE SP_BOOKS_BY_AUTHOR
@AUTHORNAME VARCHAR(100)
AS
BEGIN
SELECT B.*
FROM BOOK B
JOIN AUTHOR A ON B.AUTHORID=A.AUTHORID
WHERE A.AUTHORNAME=@AUTHORNAME;
END

EXEC SP_BOOKS_BY_AUTHOR 'J.K. ROWLING';
--10. CREATE A STORED PROCEDURE THAT ACCEPTS A PUBLICATION YEAR AND DISPLAYS BOOKS PUBLISHED AFTER THAT YEAR.

CREATE OR ALTER PROCEDURE SP_BOOKS_AFTER_YEAR
@YEAR INT
AS
BEGIN
SELECT * FROM BOOK
WHERE PUBLICATIONYEAR>@YEAR;
END


--11. CREATE A STORED PROCEDURE THAT ACCEPTS A COUNTRY NAME AND DISPLAYS ALL AUTHORS FROM THAT COUNTRY WITH
--THEIR BOOKS.
CREATE OR ALTER PROCEDURE SP_AUTHOR_COUNTRY_BOOKS
@COUNTRY VARCHAR(50)
AS
BEGIN
SELECT A.*,B.*
FROM AUTHOR A
JOIN BOOK B ON A.AUTHORID=B.AUTHORID
WHERE A.COUNTRY=@COUNTRY;
END

EXEC SP_AUTHOR_COUNTRY_BOOKS 'INDIA';
--12. CREATE A STORED PROCEDURE THAT ACCEPTS A NUMBER AS INPUT AND DISPLAYS THE TOP N MOST EXPENSIVE BOOKS
--WITH AUTHOR AND PUBLISHER DETAILS.

CREATE OR ALTER PROCEDURE SP_TOP_N_EXPENSIVE_BOOKS
@N INT
AS
BEGIN
SELECT TOP (@N) B.*,A.AUTHORNAME,P.PUBLISHERNAME
FROM BOOK B
JOIN AUTHOR A ON B.AUTHORID=A.AUTHORID
JOIN PUBLISHER P ON B.PUBLISHERID=P.PUBLISHERID
ORDER BY B.PRICE DESC;
END

EXEC SP_TOP_N_EXPENSIVE_BOOKS 5;
--PART – C:

--13. CREATE A STORED PROCEDURE THAT ACCEPTS A PUBLISHER NAME AND DISPLAYS THE TOTAL NUMBER OF BOOKS
--PUBLISHED BY THAT PUBLISHER.

CREATE OR ALTER PROCEDURE SP_TOTAL_BOOKS_PUBLISHER
@PUBLISHERNAME VARCHAR(100)
AS
BEGIN
SELECT P.PUBLISHERNAME,COUNT(B.BOOKID) AS TOTAL_BOOKS
FROM PUBLISHER P
JOIN BOOK B ON P.PUBLISHERID=B.PUBLISHERID
WHERE P.PUBLISHERNAME=@PUBLISHERNAME
GROUP BY P.PUBLISHERNAME;
END

EXEC SP_TOTAL_BOOKS_PUBLISHER 'PENGUIN';
--14. CREATE A STORED PROCEDURE THAT ACCEPTS A PRICE RANGE (MIN PRICE MAX PRICE) AND DISPLAYS BOOKS WHOSE
--PRICES FALL WITHIN THAT RANGE.
CREATE OR ALTER PROCEDURE SP_BOOK_PRICE_RANGE
@MINPRICE DECIMAL(8,2),@MAXPRICE DECIMAL(8,2)
AS
BEGIN
SELECT * FROM BOOK
WHERE PRICE BETWEEN @MINPRICE AND @MAXPRICE;
END

EXEC SP_BOOK_PRICE_RANGE 200,1000;
--15. CREATE A STORED PROCEDURE THAT ACCEPTS AN AUTHOR ID AND DELETES ALL BOOKS WRITTEN BY THAT AUTHOR.

CREATE OR ALTER PROCEDURE SP_DELETE_AUTHOR_BOOKS
@AUTHORID INT
AS
BEGIN
DELETE FROM BOOK
WHERE AUTHORID=@AUTHORID;
END

EXEC SP_DELETE_AUTHOR_BOOKS 101;